target: TenYearCHD
ordinal:
- education
binary:
- male
- currentSmoker
- BPMeds
- prevalentStroke
- prevalentHyp
- diabetes
numerical:
- age
- cigsPerDay
- totChol
- sysBP
- diaBP
- BMI
- heartRate
- glucose
